### ISSUE TITLE
Are there any related papers or algorithm principles?

### ISSUE THREAD

**Issue by yuancaimaiyi** [ferreram/depth_map_2_mesh_ray_tracer#1]
@ferreram

**Comment by ferreram** [comment]
Nope, this does basically what is described in the README.md file, i.e. uses poses and calibration estimated by Colmap to raytrace images on a 3D mesh and this way compute depth maps for the images with respect to the mesh.

**Comment by yuancaimaiyi** [comment]
@ferreram  OK,Fine !
In addition, I have doubts about its practical application?
